INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (20,0,0,'Andorra','AND','AD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (784,0,0,'Emiratos Árabes Unidos','ARE','AE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (4,0,0,'Afganistán','AFG','AF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (28,0,0,'Antigua y Barbuda','ATG','AG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (660,0,0,'Anguila','AIA','AI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (8,0,0,'Albania','ALB','AL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (51,0,0,'Armenia','ARM','AM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (530,0,0,'Antillas Neerlandesas','ANT','AN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (24,0,0,'Angola','AGO','AO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (10,0,0,'Antártida','ATA','AQ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (32,0,0,'Argentina','ARG','AR',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (16,0,0,'Samoa Americana','ASM','AS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (40,0,0,'Austria','AUT','AT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (36,0,0,'Australia','AUS','AU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (533,0,0,'Aruba','ABW','AW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (248,0,0,'Islas Áland','ALA','AX',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (31,0,0,'Azerbaiyán','AZE','AZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (70,0,0,'Bosnia y Herzegovina','BIH','BA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (52,0,0,'Barbados','BRB','BB',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (50,0,0,'Bangladesh','BGD','BD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (56,0,0,'Bélgica','BEL','BE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (854,0,0,'Burkina Faso','BFA','BF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (100,0,0,'Bulgaria','BGR','BG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (48,0,0,'Bahréin','BHR','BH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (108,0,0,'Burundi','BDI','BI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (204,0,0,'Benin','BEN','BJ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (652,0,0,'San Bartolomé','BLM','BL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (60,0,0,'Bermudas','BMU','BM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (96,0,0,'Brunéi','BRN','BN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (68,0,0,'Bolivia','BOL','BO',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (76,0,0,'Brasil','BRA','BR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (44,0,0,'Bahamas','BHS','BS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (64,0,0,'Bhután','BTN','BT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (74,0,0,'Isla Bouvet','BVT','BV',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (72,0,0,'Botsuana','BWA','BW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (112,0,0,'Belarús','BLR','BY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (84,0,0,'Belice','BLZ','BZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (124,0,0,'Canadá','CAN','CA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (166,0,0,'Islas Cocos','CCK','CC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (140,0,0,'República Centro-Africana','CAF','CF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (178,0,0,'Congo','COG','CG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (756,0,0,'Suiza','CHE','CH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (384,0,0,'Costa de Marfil','CIV','CI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (184,0,0,'Islas Cook','COK','CK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (152,0,0,'Chile','CHL','CL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (120,0,0,'Camerún','CMR','CM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (156,0,0,'China','CHN','CN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (170,0,0,'Colombia','COL','CO',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (188,0,0,'Costa Rica','CRI','CR',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (192,0,0,'Cuba','CUB','CU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (132,0,0,'Cabo Verde','CPV','CV',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (162,0,0,'Islas Christmas','CXR','CX',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (196,0,0,'Chipre','CYP','CY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (203,0,0,'República Checa','CZE','CZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (276,0,0,'Alemania','DEU','DE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (262,0,0,'Yibuti','DJI','DJ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (208,0,0,'Dinamarca','DNK','DK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (212,0,0,'Domínica','DMA','DM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (214,0,0,'República Dominicana','DOM','DO',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (12,0,0,'Argel','DZA','DZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (218,0,0,'Ecuador','ECU','EC',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (233,0,0,'Estonia','EST','EE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (818,0,0,'Egipto','EGY','EG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (732,0,0,'Sahara Occidental','ESH','EH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (232,0,0,'Eritrea','ERI','ER',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (724,0,0,'España','ESP','ES',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (231,0,0,'Etiopía','ETH','ET',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (246,0,0,'Finlandia','FIN','FI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (242,0,0,'Fiji','FJI','FJ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (238,0,0,'Islas Malvinas','KLK','FK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (583,0,0,'Micronesia','FSM','FM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (234,0,0,'Islas Faroe','FRO','FO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (250,0,0,'Francia','FRA','FR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (266,0,0,'Gabón','GAB','GA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (826,0,0,'Reino Unido','GBR','GB',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (308,0,0,'Granada','GRD','GD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (268,0,0,'Georgia','GEO','GE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (254,0,0,'Guayana Francesa','GUF','GF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (831,0,0,'Guernsey','GGY','GG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (288,0,0,'Ghana','GHA','GH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (292,0,0,'Gibraltar','GIB','GI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (304,0,0,'Groenlandia','GRL','GL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (270,0,0,'Gambia','GMB','GM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (324,0,0,'Guinea','GIN','GN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (312,0,0,'Guadalupe','GLP','GP',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (226,0,0,'Guinea Ecuatorial','GNQ','GQ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (300,0,0,'Grecia','GRC','GR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (239,0,0,'Georgia del Sur e Islas Sandwich del Sur','SGS','GS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (320,0,0,'Guatemala','GTM','GT',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (316,0,0,'Guam','GUM','GU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (624,0,0,'Guinea-Bissau','GNB','GW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (328,0,0,'Guayana','GUY','GY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (344,0,0,'Hong Kong','HKG','HK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (334,0,0,'Islas Heard y McDonald','HMD','HM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (340,0,0,'Honduras','HND','HN',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (191,0,0,'Croacia','HRV','HR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (332,0,0,'Haití','HTI','HT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (348,0,0,'Hungría','HUN','HU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (360,0,0,'Indonesia','IDN','ID',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (372,0,0,'Irlanda','IRL','IE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (376,0,0,'Israel','ISR','IL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (833,0,0,'Isla de Man','IMN','IM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (356,0,0,'India','IND','IN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (86,0,0,'Territorio Británico del Océano Índico','IOT','IO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (368,0,0,'Irak','IRQ','IQ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (364,0,0,'Irán','IRN','IR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (352,0,0,'Islandia','ISL','IS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (380,0,0,'Italia','ITA','IT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (832,0,0,'Jersey','JEY','JE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (388,0,0,'Jamaica','JAM','JM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (400,0,0,'Jordania','JOR','JO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (392,0,0,'Japón','JPN','JP',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (404,0,0,'Kenia','KEN','KE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (417,0,0,'Kirguistán','KGZ','KG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (116,0,0,'Camboya','KHM','KH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (296,0,0,'Kiribati','KIR','KI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (174,0,0,'Comoros','COM','KM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (659,0,0,'San Cristóbal y Nieves','KNA','KN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (408,0,0,'Corea del Norte','PRK','KP',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (410,0,0,'Corea del Sur','KOR','KR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (414,0,0,'Kuwait','KWT','KW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (136,0,0,'Islas Caimán','CYM','KY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (398,0,0,'Kazajstán','KAZ','KZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (418,0,0,'Laos','LAO','LA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (422,0,0,'Líbano','LBN','LB',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (662,0,0,'Santa Lucía','LCA','LC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (438,0,0,'Liechtenstein','LIE','LI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (144,0,0,'Sri Lanka','LKA','LK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (430,0,0,'Liberia','LBR','LR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (426,0,0,'Lesotho','LSO','LS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (440,0,0,'Lituania','LTU','LT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (442,0,0,'Luxemburgo','LUX','LU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (428,0,0,'Letonia','LVA','LV',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (434,0,0,'Libia','LBY','LY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (504,0,0,'Marruecos','MAR','MA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (492,0,0,'Mónaco','MCO','MC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (498,0,0,'Moldova','MDA','MD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (499,0,0,'Montenegro','MNE','ME',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (450,0,0,'Madagascar','MDG','MG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (584,0,0,'Islas Marshall','MHL','MH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (807,0,0,'Macedonia','MKD','MK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (466,0,0,'Mali','MLI','ML',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (104,0,0,'Myanmar','MMR','MM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (496,0,0,'Mongolia','MNG','MN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (446,0,0,'Macao','MAC','MO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (474,0,0,'Martinica','MTQ','MQ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (478,0,0,'Mauritania','MRT','MR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (500,0,0,'Montserrat','MSR','MS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (470,0,0,'Malta','MLT','MT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (480,0,0,'Mauricio','MUS','MU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (462,0,0,'Maldivas','MDV','MV',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (454,0,0,'Malawi','MWI','MW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (484,0,0,'México','MEX','MX',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (458,0,0,'Malasia','MYS','MY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (508,0,0,'Mozambique','MOZ','MZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (516,0,0,'Namibia','NAM','NA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (540,0,0,'Nueva Caledonia','NCL','NC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (562,0,0,'Níger','NER','NE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (574,0,0,'Islas Norkfolk','NFK','NF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (566,0,0,'Nigeria','NGA','NG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (558,0,0,'Nicaragua','NIC','NI',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (528,0,0,'Países Bajos','NLD','NL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (578,0,0,'Noruega','NOR','NO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (524,0,0,'Nepal','NPL','NP',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (520,0,0,'Nauru','NRU','NR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (570,0,0,'Niue','NIU','NU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (554,0,0,'Nueva Zelanda','NZL','NZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (512,0,0,'Omán','OMN','OM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (591,0,0,'Panamá','PAN','PA',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (604,0,0,'Perú','PER','PE',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (258,0,0,'Polinesia Francesa','PYF','PF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (598,0,0,'Papúa Nueva Guinea','PNG','PG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (608,0,0,'Filipinas','PHL','PH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (586,0,0,'Pakistán','PAK','PK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (616,0,0,'Polonia','POL','PL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (666,0,0,'San Pedro y Miquelón','SPM','PM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (612,0,0,'Islas Pitcairn','PCN','PN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (630,0,0,'Puerto Rico','PRI','PR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (275,0,0,'Palestina','PSE','PS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (620,0,0,'Portugal','PRT','PT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (585,0,0,'Islas Palaos','PLW','PW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (600,0,0,'Paraguay','PRY','PY',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (634,0,0,'Qatar','QAT','QA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (638,0,0,'Reunión','REU','RE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (642,0,0,'Rumanía','ROU','RO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (688,0,0,'Serbia y Montenegro','SRB','RS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (643,0,0,'Rusia','RUS','RU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (646,0,0,'Ruanda','RWA','RW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (682,0,0,'Arabia Saudita','SAU','SA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (90,0,0,'Islas Solomón','SLB','SB',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (690,0,0,'Seychelles','SYC','SC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (736,0,0,'Sudán','SDN','SD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (752,0,0,'Suecia','SWE','SE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (702,0,0,'Singapur','SGP','SG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (654,0,0,'Santa Elena','SHN','SH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (705,0,0,'Eslovenia','SVN','SI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (744,0,0,'Islas Svalbard y Jan Mayen','SJM','SJ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (703,0,0,'Eslovaquia','SVK','SK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (694,0,0,'Sierra Leona','SLE','SL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (674,0,0,'San Marino','SMR','SM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (686,0,0,'Senegal','SEN','SN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (706,0,0,'Somalia','SOM','SO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (740,0,0,'Surinam','SUR','SR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (678,0,0,'Santo Tomé y Príncipe','STP','ST',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (222,0,0,'El Salvador','SLV','SV',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (760,0,0,'Siria','SYR','SY',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (748,0,0,'Suazilandia','SWZ','SZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (796,0,0,'Islas Turcas y Caicos','TCA','TC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (148,0,0,'Chad','TCD','TD',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (260,0,0,'Territorios Australes Franceses','ATF','TF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (768,0,0,'Togo','TGO','TG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (764,0,0,'Tailandia','THA','TH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (834,0,0,'Tanzania','TZA','TH',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (762,0,0,'Tayikistán','TJK','TJ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (772,0,0,'Tokelau','TKL','TK',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (626,0,0,'Timor-Leste','TLS','TL',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (795,0,0,'Turkmenistán','TKM','TM',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (788,0,0,'Túnez','TUN','TN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (776,0,0,'Tonga','TON','TO',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (792,0,0,'Turquía','TUR','TR',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (780,0,0,'Trinidad y Tobago','TTO','TT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (798,0,0,'Tuvalu','TUV','TV',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (158,0,0,'Taiwán','TWN','TW',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (804,0,0,'Ucrania','UKR','UA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (800,0,0,'Uganda','UGA','UG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (840,0,0,'Estados Unidos de América','USA','US',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (858,0,0,'Uruguay','URY','UY',1)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (860,0,0,'Uzbekistán','UZB','UZ',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (336,0,0,'Ciudad del Vaticano','VAT','VA',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (670,0,0,'San Vicente y las Granadinas','VCT','VC',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (862,0,0,'Venezuela','VEN','VE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (92,0,0,'Islas Vírgenes Británicas','VGB','VG',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (850,0,0,'Islas Vírgenes de los Estados Unidos de América','VIR','VI',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (704,0,0,'Vietnam','VNM','VN',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (548,0,0,'Vanuatu','VUT','VU',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (876,0,0,'Wallis y Futuna','WLF','WF',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (882,0,0,'Samoa','WSM','WS',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (887,0,0,'Yemen','YEM','YE',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (175,0,0,'Mayotte','MYT','YT',0)
INSERT INTO [dbo].[paises] (iso_numerico,dsblPaises,dplyPaises,iso_nombre,iso_alfa3,iso_alfa2,es_dichter) VALUES (710,0,0,'Sudáfrica','ZAF','ZA',0)
